#!/usr/bin/env bash

case "$1" in
    docker)
        echo "### building weekresolver docker ###"
        docker build -f target/docker/Dockerfile --pull --no-cache . -t docker-metascrum.artifacts.dbccloud.dk/weekresolver:devel || exit 1
        if [[ ! -z "$BUILD_NUMBER" ]]; then
            docker tag docker-metascrum.artifacts.dbccloud.dk/weekresolver:devel docker-metascrum.artifacts.dbccloud.dk/weekresolver:${BRANCH_NAME}-${BUILD_NUMBER}
        fi
        ;;

    *)
        echo "### building weekresolver project ###"
        echo "### Look for build artifacts in target/ ###"

        mvn package -Dmaven.test.skip=true || exit 1
        ;;
esac

